import {createRoot} from 'react-dom/client';
import OrderReceipt from '@/components/customer-orders/OrderReceipt';
import SignInForm from '@/components/customer-orders/SignInForm';
import {presentOrder} from '@/lib/customer-orders/presentation';
import '@/app/(customer)/customer.css';
const params=new URLSearchParams(location.search);
const order=presentOrder({id:'10000000-0000-0000-0000-000000000001',order_number:'ECL-1042',created_at:'2026-09-27T01:00:00Z',paid_at:'2026-09-27T04:00:00Z',shipped_at:'2026-09-29T01:00:00Z',status:'shipped',payment_method:'payid',carrier_code:'auspost',tracking_number:'SAMPLE-TRACKING',subtotal_cents:17700,discount_cents:1770,shipping_cents:1000,total_cents:16930,refunded_cents:0,customer_email:'sample@example.test',customer_name:'Sample Customer',shipping_address:{line1:'123 Example Street',suburb:'Melbourne',state:'VIC',postcode:'3000',country:'Australia'},order_items:[{id:'1',product_name:'GHK-Cu',size_label_snapshot:'50 mg',variant_label:'1 vial',qty:2,refunded_qty:0,line_total_cents:11800,discount_allocated_cents:1180,image_url_snapshot:'/images/products/ghk-cu-50mg-labelled.webp'},{id:'2',product_name:'GHK-Cu',size_label_snapshot:'100 mg',variant_label:'1 vial',qty:1,refunded_qty:0,line_total_cents:5900,discount_allocated_cents:590,image_url_snapshot:'/images/products/ghk-cu-100mg-labelled.webp'}]},params.get('owner')==='1');
order.items=order.items.map(i=>({...i,imageUrl:params.has('no-images')?null:i.imageUrl?new URL(i.imageUrl).pathname:null}));
function App(){return <div className="co-shell"><header className="co-header"><a href="/customer-order.html" className="co-wordmark">EAST COAST <strong>LABS</strong><span>AUSTRALIAN RESEARCH SUPPLY</span></a><nav aria-label="Customer navigation"><a href="/customer-order.html?signin=1">My orders</a></nav></header><main className="co-main">{params.has('signin')?<section className="co-card co-signin"><p className="co-eyebrow">Your East Coast Labs account</p><h1>Your orders, made simple</h1><p>Review purchases, follow dispatch updates and find your delivery details.</p><SignInForm returnTo="/account/orders"/></section>:<div className="co-receipt"><div className="co-page-heading"><div><p className="co-eyebrow">Your order</p><h1>ECL-1042</h1><p>Placed 27 Sept 2026</p></div><a href="/customer-order.html?signin=1" className="co-secondary">My orders</a></div><OrderReceipt order={order}/>{!order.privateDetails&&<aside className="co-signin-note"><h2>All your orders, in one place</h2><p>Sign in with the email you used at checkout to see your full receipt, delivery address and order history.</p><a href="/customer-order.html?signin=1" className="co-secondary">Sign in with email</a></aside>}</div>}</main><footer className="co-footer"><p>Sample preview · Nothing is sent</p><p>East Coast Labs · Research use only.</p></footer></div>}
createRoot(document.getElementById('root')!).render(<App/>);
