// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {act,cleanup,render,screen,fireEvent} from '@testing-library/react';
import {makeOrderPreview,makeWorkspaceParams} from '../helpers/order-workspace-fixtures';
vi.mock('@/app/admin/(dashboard)/orders/actions',()=>({confirmPayment:vi.fn()}));
import OrderPreviewDrawer from '@/components/admin/OrderPreviewDrawer';
beforeEach(()=>{HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};});
afterEach(cleanup);
const callbacks=()=>({onClose:vi.fn(),onNavigate:vi.fn(),onMutated:vi.fn(),onRestoreFocus:vi.fn()});
it('aborts previous loads and ignores a late response after another order opens',async()=>{const a=makeOrderPreview(),b=makeOrderPreview({id:'10000000-0000-4000-8000-000000000002',order_number:'ECL-1049'});const resolvers=new Map<string,(v:Response)=>void>(),signals:AbortSignal[]=[];vi.stubGlobal('fetch',vi.fn((url:string,opts:RequestInit)=>{signals.push(opts.signal as AbortSignal);return new Promise(resolve=>resolvers.set(url,resolve));}));const p={params:makeWorkspaceParams(),neighborIds:[a.facts.id,b.facts.id],...callbacks()};const {rerender}=render(<OrderPreviewDrawer {...p} id={a.facts.id}/>);rerender(<OrderPreviewDrawer {...p} id={b.facts.id}/>);expect(signals[0].aborted).toBe(true);await act(async()=>resolvers.get(`/admin/orders/${b.facts.id}/preview`)!(Response.json(b)));expect(screen.getByRole('heading',{name:'Order ECL-1049'})).toBeVisible();await act(async()=>resolvers.get(`/admin/orders/${a.facts.id}/preview`)!(Response.json(a)));expect(screen.queryByRole('heading',{name:'Order ECL-1048'})).not.toBeInTheDocument();expect(screen.getByRole('link',{name:'Open full order'})).toHaveAttribute('href',expect.stringContaining('returnTo='));});
it.each([404,500,403])('keeps the list intact on status %s and offers recovery',async status=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(Response.json({}, {status})));render(<OrderPreviewDrawer id={makeOrderPreview().facts.id} params={makeWorkspaceParams()} neighborIds={[]} {...callbacks()}/>);expect(await screen.findByRole('alert')).toHaveTextContent(status===404?'Order no longer available':status===403?'Sign in again':'Unable to load');expect(screen.getByRole('button',{name:'Close order'})).toBeEnabled();});
it('requires discard before leaving a draft and restores focus/body scroll',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(Response.json(makeOrderPreview({status:'pending'}))));const cb=callbacks();const {unmount}=render(<OrderPreviewDrawer id={makeOrderPreview().facts.id} params={makeWorkspaceParams()} neighborIds={[]} {...cb}/>);await screen.findByLabelText('Payment reference');fireEvent.change(screen.getByLabelText('Payment reference'),{target:{value:'draft'}});fireEvent.click(screen.getByRole('button',{name:'Close order'}));expect(cb.onClose).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Discard changes'}));expect(cb.onClose).toHaveBeenCalledOnce();unmount();expect(document.body.style.overflow).toBe('');expect(cb.onRestoreFocus).toHaveBeenCalled();});
it('treats a non-JSON login document as expired authentication',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('<html>login</html>',{headers:{'content-type':'text/html'}})));render(<OrderPreviewDrawer id={makeOrderPreview().facts.id} params={makeWorkspaceParams()} neighborIds={[]} {...callbacks()}/>);expect(await screen.findByRole('alert')).toHaveTextContent('Sign in again');});
it('blocks Escape while a payment write is in flight',async()=>{const {confirmPayment}=await import('@/app/admin/(dashboard)/orders/actions');vi.mocked(confirmPayment).mockImplementation(()=>new Promise(()=>{}));vi.stubGlobal('fetch',vi.fn().mockResolvedValue(Response.json(makeOrderPreview({status:'pending'}))));const cb=callbacks();render(<OrderPreviewDrawer id={makeOrderPreview().facts.id} params={makeWorkspaceParams()} neighborIds={[]} {...cb}/>);await screen.findByLabelText('Payment reference');fireEvent.click(screen.getByText('Review payment'));fireEvent.click(screen.getByText('Confirm payment'));fireEvent(screen.getByRole('dialog'),new Event('cancel',{cancelable:true}));expect(cb.onClose).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Close order'})).toBeDisabled();});
