import {beforeEach,it,expect,vi} from 'vitest';
import {makeWorkspacePage,makeWorkspaceParams,makeWorkspaceRow} from '../helpers/order-workspace-fixtures';
const {rpc}=vi.hoisted(()=>({rpc:vi.fn()}));vi.mock('@/lib/admin/db',()=>({adminDb:()=>({rpc})}));
import {getOrderWorkspace,getOrderWorkspaceRow,getOrderWorkspaceExport} from '@/lib/admin/order-workspace/queries';
beforeEach(()=>{rpc.mockReset();rpc.mockResolvedValue({data:makeWorkspacePage([makeWorkspaceRow()]),error:null});});
it('sends only population parameters with Sydney inclusive-day boundaries',async()=>{
 const r=await getOrderWorkspace(makeWorkspaceParams({from:'2026-10-04',to:'2026-10-04',q:'a,(%)',discount:'VIP',order:makeWorkspaceRow().id}));
 expect(r.total).toBe(1);expect(rpc).toHaveBeenCalledWith('admin_order_workspace',{p_filters:{status:'to_fulfil',q:'a,(%)',from_at:'2026-10-03T14:00:00.000Z',to_at:'2026-10-04T13:00:00.000Z',discount:'VIP',shipping:'any',sort:'waiting_seconds',dir:'desc',page:1}});
});
it.each([{id:'bad'},{status:'delivered'},{total_cents:-1},{line_count:1.2},{remaining_physical_units:Number.MAX_SAFE_INTEGER+1},{paid_at:'bad'},{issue_keys:['madeup']},{items:[{id:'bad'}]}])('rejects malformed row %j',async patch=>{rpc.mockResolvedValue({data:makeWorkspacePage([makeWorkspaceRow(patch as never)]),error:null});await expect(getOrderWorkspace(makeWorkspaceParams())).rejects.toThrow(/Invalid orders workspace/);});
it.each([{as_of:'bad'},{counts:{}},{rows:Array(26).fill(makeWorkspaceRow())},{page:0}])('rejects malformed envelope %j',async patch=>{rpc.mockResolvedValue({data:{...makeWorkspacePage(),...patch},error:null});await expect(getOrderWorkspace(makeWorkspaceParams())).rejects.toThrow(/Invalid orders workspace/);});
it('keeps total larger than the page, while propagating database errors',async()=>{rpc.mockResolvedValueOnce({data:{...makeWorkspacePage(),total:90},error:null});expect((await getOrderWorkspace(makeWorkspaceParams())).total).toBe(90);rpc.mockResolvedValueOnce({error:{message:'unavailable'}});await expect(getOrderWorkspace(makeWorkspaceParams())).rejects.toThrow('unavailable');});
it('bounds individual reads to the requested ID and distinguishes missing from failed',async()=>{const row=makeWorkspaceRow();rpc.mockResolvedValueOnce({data:[{facts:row}],error:null});expect(await getOrderWorkspaceRow(row.id)).toEqual(row);expect(rpc).toHaveBeenLastCalledWith('admin_order_workspace_scope',{p_filters:{},p_order_ids:[row.id],p_as_of:expect.any(String)});rpc.mockResolvedValueOnce({data:[],error:null});expect(await getOrderWorkspaceRow(row.id)).toBeNull();rpc.mockResolvedValueOnce({data:[{facts:makeWorkspaceRow({id:'00000000-0000-4000-8000-000000000009'})}],error:null});await expect(getOrderWorkspaceRow(row.id)).rejects.toThrow();await expect(getOrderWorkspaceRow('bad')).rejects.toThrow();});
it('rejects export truncation',async()=>{rpc.mockResolvedValueOnce({data:{rows:[],total:26,as_of:new Date().toISOString()},error:null});await expect(getOrderWorkspaceExport(makeWorkspaceParams())).rejects.toThrow(/Invalid/);});
