// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {useState} from 'react';
import {afterEach,it,expect,vi} from 'vitest';
import {act,cleanup,render,screen,fireEvent} from '@testing-library/react';
import {parseOrderWorkspaceParams,rawOrderParams} from '@/lib/admin/order-workspace/params';
import {makeWorkspacePage} from '../helpers/order-workspace-fixtures';
const nav=vi.hoisted(()=>({href:'',set:(_href:string)=>{},push:vi.fn(),replace:vi.fn(),refresh:vi.fn()}));
vi.mock('next/navigation',()=>({useRouter:()=>({push:(href:string)=>{nav.push(href);nav.set(href);},replace:(href:string)=>{nav.replace(href);nav.set(href);},refresh:nav.refresh})}));
vi.mock('@/app/admin/(dashboard)/orders/actions',()=>({confirmPayment:vi.fn(),bulkConfirmPayment:vi.fn(),bulkReinstate:vi.fn()}));
import OrdersWorkspace from '@/components/admin/OrdersWorkspace';
function renderWorkspace(query=''){nav.push.mockClear();nav.replace.mockClear();function Harness(){const [href,setHref]=useState(`/admin/orders${query}`);nav.href=href;nav.set=setHref;const params=parseOrderWorkspaceParams(rawOrderParams(new URL(href,'http://test').searchParams));return <OrdersWorkspace params={params} data={{...makeWorkspacePage(),total:80,page:params.page}} adminUserId="test"/>;}render(<Harness/>);return ()=>parseOrderWorkspaceParams(rawOrderParams(new URL(nav.href,'http://test').searchParams));}
afterEach(()=>{cleanup();localStorage.clear();vi.useRealTimers();});
it('does not navigate on hydration and retains filters through sorting/page/view changes',()=>{const current=renderWorkspace('?status=to_fulfil&discount=VIP_20&shipping=express&page=3&from=2026-09-01');expect(nav.push).not.toHaveBeenCalled();expect(nav.replace).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Sort orders'),{target:{value:'total_cents'}});expect(current()).toMatchObject({discount:'VIP_20',shipping:'express',sort:'total_cents',dir:'desc',page:1,from:'2026-09-01'});fireEvent.click(screen.getByRole('button',{name:'Next page'}));expect(current().page).toBe(2);fireEvent.click(screen.getByRole('button',{name:/Awaiting payment/}));expect(current()).toMatchObject({status:'pending',page:1,discount:'VIP_20'});fireEvent.click(screen.getByRole('button',{name:'Remove discount filter'}));expect(current()).toMatchObject({discount:'',from:'2026-09-01'});fireEvent.click(screen.getByText('Clear filters'));expect(current()).toMatchObject({status:'pending',from:'',shipping:'any'});});
it('debounces literal search, applies Enter, and cancels stale typing on restored URL',()=>{vi.useFakeTimers();const current=renderWorkspace('?q=old');expect(current().status).toBe('all');fireEvent.change(screen.getByLabelText('Search orders'),{target:{value:'ref(1),20%_'}});act(()=>vi.advanceTimersByTime(300));expect(current().q).toBe('ref(1),20%_');fireEvent.change(screen.getByLabelText('Search orders'),{target:{value:'instant'}});fireEvent.keyDown(screen.getByLabelText('Search orders'),{key:'Enter'});expect(current().q).toBe('instant');fireEvent.change(screen.getByLabelText('Search orders'),{target:{value:'stale'}});act(()=>nav.set('/admin/orders?status=shipped&q=restored'));act(()=>vi.advanceTimersByTime(500));expect(screen.getByLabelText('Search orders')).toHaveValue('restored');expect(current().status).toBe('shipped');});
it('saves and applies a view without persisting search',()=>{const current=renderWorkspace('?status=pending&q=private');fireEvent.click(screen.getByText('Save view'));fireEvent.change(screen.getByLabelText('View name'),{target:{value:'Payments'}});fireEvent.click(screen.getByRole('button',{name:'Save'}));const select=screen.getByLabelText('Saved views') as HTMLSelectElement;fireEvent.change(select,{target:{value:select.options[1].value}});expect(current()).toMatchObject({status:'pending',q:'',page:1});});
