// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {afterEach,it,expect,vi} from 'vitest';
import {cleanup,render,screen,fireEvent} from '@testing-library/react';
import OrderWorkspaceTable,{type OrderListProps} from '@/components/admin/OrderWorkspaceTable';
import OrderCards from '@/components/admin/OrderCards';
import {makeWorkspaceParams,makeWorkspaceRow} from '../helpers/order-workspace-fixtures';
const props=():OrderListProps=>({rows:[makeWorkspaceRow(),makeWorkspaceRow({id:'10000000-0000-4000-8000-000000000002',order_number:'ECL-1049'})],params:makeWorkspaceParams(),selectedIds:new Set(),columns:['identity','items','shipping','waiting','total'],density:'comfortable',onToggle:vi.fn(),onTogglePage:vi.fn(),onOpen:vi.fn(),onSort:vi.fn(),dialogOpen:false});
afterEach(cleanup);
it('uses a mixed page checkbox, sortable headers, and separate selection targets',()=>{const p=props();p.selectedIds=new Set([p.rows[0].id]);render(<OrderWorkspaceTable {...p}/>);expect(screen.getByLabelText('Select all orders on this page')).toHaveProperty('indeterminate',true);expect(screen.getByRole('columnheader',{name:/Waiting/})).toHaveAttribute('aria-sort','descending');fireEvent.click(screen.getByLabelText('Select ECL-1048'));expect(p.onToggle).toHaveBeenCalledWith(p.rows[0].id);expect(p.onOpen).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Sort by Total'}));expect(p.onSort).toHaveBeenCalledWith('total_cents','desc');});
it('preserves native modified links and supports row shortcuts without hijacking inputs',()=>{const p=props();render(<OrderWorkspaceTable {...p}/>);const link=screen.getByRole('link',{name:'ECL-1048'});expect(link).toHaveAttribute('href',expect.stringContaining(`/admin/orders/${p.rows[0].id}`));fireEvent.click(link,{ctrlKey:true});expect(p.onOpen).not.toHaveBeenCalled();fireEvent.click(link);expect(p.onOpen).toHaveBeenCalledWith(p.rows[0].id,link);const row=link.closest('tr')!;row.focus();fireEvent.keyDown(row,{key:'j'});expect(document.activeElement).toBe(screen.getByRole('link',{name:'ECL-1049'}).closest('tr'));fireEvent.keyDown(document.activeElement!,{key:'x'});expect(p.onToggle).toHaveBeenCalledWith(p.rows[1].id);p.onToggle=vi.fn();fireEvent.keyDown(screen.getByLabelText('Select ECL-1048'),{key:'x'});});
it('suppresses row shortcuts while a dialog owns focus',()=>{const p=props();render(<OrderWorkspaceTable {...p} dialogOpen/>);fireEvent.keyDown(screen.getByRole('link',{name:'ECL-1048'}).closest('tr')!,{key:'Enter'});expect(p.onOpen).not.toHaveBeenCalled();});
it('keeps unknown physical units, shipping, issues and honest statuses on cards',()=>{const p=props();render(<OrderCards {...p} rows={[makeWorkspaceRow({remaining_physical_units:null,paid_at:null,waiting_seconds:null,issue_keys:['quantity_unknown']})]}/>);expect(screen.getByText('Express')).toBeVisible();expect(screen.getByText('Physical quantity unavailable')).toBeVisible();expect(screen.getByText('Payment time unavailable')).toBeVisible();expect(screen.getByText('Packing quantity unavailable')).toBeVisible();expect(screen.getByRole('button',{name:/Open order/})).toBeEnabled();});
it('shows size, line count, more items and issues even with optional columns removed',()=>{const p=props();const {rerender}=render(<OrderWorkspaceTable {...p} rows={[makeWorkspaceRow({line_count:12,issue_keys:['address_incomplete']})]}/>);expect(screen.getByText('10 mg')).toBeVisible();expect(screen.getByText('12 line items · 6 physical units')).toBeVisible();expect(screen.getByRole('button',{name:'+11 more items'})).toBeEnabled();rerender(<OrderWorkspaceTable {...p} columns={['identity','total']} rows={[makeWorkspaceRow({customer_name:null,issue_keys:['address_incomplete']})]}/>);expect(screen.getByText('Address needs review')).toBeVisible();expect(screen.getByText('alex@example.test')).toBeVisible();});
it('never labels internal completion as delivery or a refund as a transfer',()=>{render(<OrderCards {...props()} rows={[makeWorkspaceRow({status:'completed',refunded_cents:1000,shipped_at:'2026-09-29T02:00:00Z'})]}/>);expect(screen.getByText('Completed (internal)')).toBeVisible();expect(screen.queryByText('Delivered')).not.toBeInTheDocument();expect(screen.getByText('Partial refund recorded')).toBeVisible();expect(screen.getByText(/transfer outstanding/)).toBeVisible();});
