// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {afterEach,it,expect,vi} from 'vitest';
import {act,cleanup,render,screen,fireEvent} from '@testing-library/react';
const {advance,push}=vi.hoisted(()=>({advance:vi.fn(),push:vi.fn()}));vi.mock('@/app/admin/(dashboard)/orders/actions',()=>({advanceStatus:advance}));vi.mock('next/navigation',()=>({useRouter:()=>({push,refresh:vi.fn()})}));vi.mock('sonner',()=>({toast:{error:vi.fn(),success:vi.fn()}}));
import PackingMode,{type PackOrder} from '@/components/admin/PackingMode';
const order:PackOrder={id:'one',orderNumber:'ECL-1',customerName:'Sample',customerEmail:'sample@example.test',address:null,totalCents:1000,notes:null,items:[{id:'item',productName:'Sample product',variantLabel:'single',sku:'S',qty:1,refundedQty:0,lineTotalCents:1000}]};
afterEach(()=>{cleanup();advance.mockReset();push.mockReset();});
it('returns the final selected parcel to its saved query and prevents duplicate submits',async()=>{let resolve!:(v:unknown)=>void;advance.mockImplementation(()=>new Promise(r=>resolve=r));render(<PackingMode order={order} nextId={null} position={2} total={2} nextHref={null} exitHref="/admin/orders?status=to_fulfil&page=3"/>);fireEvent.change(screen.getByLabelText('Tracking number'),{target:{value:'TRACK-1'}});fireEvent.click(screen.getByText('Mark shipped anyway'));fireEvent.click(screen.getByRole('button',{name:'Mark shipped'}));expect(advance).toHaveBeenCalledTimes(1);await act(async()=>resolve({ok:true}));expect(push).toHaveBeenCalledWith('/admin/orders?status=to_fulfil&page=3');});
it('keeps tracking on an action failure and resets all parcel state when identity changes',async()=>{advance.mockResolvedValue({ok:false,error:'Allocate lots first'});const {rerender}=render(<PackingMode order={order} nextId="two" position={1} total={2} nextHref="/admin/orders/two/pack?batch=one,two"/>);fireEvent.click(screen.getByRole('button',{name:/Sample product/}));fireEvent.change(screen.getByLabelText('Tracking number'),{target:{value:'TRACK'}});fireEvent.click(screen.getByText('Packed — mark shipped'));await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Mark shipped'})));expect(screen.getByLabelText('Tracking number')).toHaveValue('TRACK');rerender(<PackingMode order={{...order,id:'two'}} nextId={null} position={2} total={2}/>);expect(screen.getByLabelText('Tracking number')).toHaveValue('');expect(screen.getByRole('button',{name:/Sample product/})).toHaveAttribute('aria-pressed','false');});
