// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {useState} from 'react';
import {afterEach,it,expect,vi} from 'vitest';
import {cleanup,render,screen,fireEvent} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {makeWorkspaceParams,makeWorkspaceRow} from '../helpers/order-workspace-fixtures';
import type {OrderWorkspaceRow} from '@/lib/admin/order-workspace/types';
const {confirm,reinstate}=vi.hoisted(()=>({confirm:vi.fn(),reinstate:vi.fn()}));vi.mock('@/app/admin/(dashboard)/orders/actions',()=>({bulkConfirmPayment:confirm,bulkReinstate:reinstate}));
import OrdersBulkActions,{type OrderBulkResult} from '@/components/admin/OrdersBulkActions';
import {useOrderSelection} from '@/components/admin/useOrderSelection';
function Harness({rows}:{rows:OrderWorkspaceRow[]}){const selection=useOrderSelection(rows,'a'),[report,setReport]=useState<OrderBulkResult|null>(null);return <><label><input type="checkbox" aria-label="Select all orders on this page" onChange={selection.togglePage}/>Select page</label>{rows.map(r=><input key={r.id} type="checkbox" aria-label={`Select ${r.order_number}`} checked={selection.selectedIds.has(r.id)} onChange={()=>selection.toggle(r.id)}/>)}<OrdersBulkActions rows={rows} params={makeWorkspaceParams()} selection={selection} report={report} onResult={setReport} onDismiss={()=>setReport(null)} reinstatable={Object.fromEntries(rows.map(r=>[r.id,{recoverable:true,short:0}]))}/></>;}
afterEach(()=>{cleanup();confirm.mockReset();reinstate.mockReset();});
it('retains only failed visible payments for retry',async()=>{const user=userEvent.setup(),a=makeWorkspaceRow({status:'pending'}),b=makeWorkspaceRow({status:'pending',id:'10000000-0000-4000-8000-000000000002',order_number:'ECL-1049'});confirm.mockResolvedValueOnce({ok:true,moved:1,failed:[{id:b.id,error:'Stock no longer available'}]}).mockResolvedValueOnce({ok:true,moved:1,failed:[]});render(<Harness rows={[a,b]}/>);await user.click(screen.getByLabelText('Select all orders on this page'));await user.click(screen.getByRole('button',{name:'Confirm 2 payments'}));await user.click(screen.getByRole('button',{name:'Confirm payments'}));expect(confirm).toHaveBeenCalledWith([a.id,b.id]);expect(await screen.findByText('Stock no longer available')).toBeVisible();expect(screen.getByLabelText('Select ECL-1048')).not.toBeChecked();expect(screen.getByLabelText('Select ECL-1049')).toBeChecked();await user.click(screen.getByRole('button',{name:'Confirm 1 payment'}));await user.click(screen.getByRole('button',{name:'Confirm payments'}));expect(confirm).toHaveBeenLastCalledWith([b.id]);});
it('derives mixed eligibility, packing order and printing from current visible rows',()=>{const rows=['paid','pending','processing','shipped','cancelled'].map((status,i)=>makeWorkspaceRow({status:status as OrderWorkspaceRow['status'],id:`10000000-0000-4000-8000-00000000000${i+1}`,order_number:`ECL-${i}`}));const {rerender}=render(<Harness rows={rows}/>);fireEvent.click(screen.getByLabelText('Select all orders on this page'));expect(screen.getByText('5 selected on this page')).toBeVisible();expect(screen.getByRole('link',{name:'Prepare packing (2)'})).toHaveAttribute('href',expect.stringContaining(encodeURIComponent(`${rows[0].id},${rows[2].id}`)));expect(screen.getByRole('link',{name:'Print 5 slips'})).toHaveAttribute('href',expect.stringContaining('ids='));expect(screen.getByRole('button',{name:'Reinstate 1 order'})).toBeEnabled();rerender(<Harness rows={rows.map(r=>({...r,status:'shipped'}))}/>);expect(screen.queryByRole('button',{name:'Confirm 1 payment'})).not.toBeInTheDocument();expect(screen.getByText('No selected orders are eligible for payment, packing or reinstatement.')).toBeVisible();});
