// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {render,cleanup,screen} from '@testing-library/react';
import {makeOrderPreview} from '../helpers/order-workspace-fixtures';
const m=vi.hoisted(()=>({guard:vi.fn(),order:vi.fn(),selected:vi.fn(),global:vi.fn(),lots:vi.fn(),fulfilment:vi.fn()}));
vi.mock('@/lib/admin/auth',()=>({requireAdmin:m.guard}));vi.mock('@/lib/admin/order-queries',()=>({getOrder:m.order}));vi.mock('@/lib/admin/packing',()=>({selectedPackContext:m.selected,packQueuePosition:m.global}));vi.mock('@/lib/admin/fulfilment',()=>({getOrderFulfilment:m.fulfilment,getLotCatalog:m.lots}));vi.mock('@/components/admin/LotPacking',()=>({default:()=>null}));vi.mock('@/components/admin/PackingMode',()=>({default:(props:unknown)=><div>{JSON.stringify(props)}</div>}));vi.mock('next/navigation',()=>({notFound:()=>{throw Error('NOT_FOUND');}}));
import PackPage from '@/app/admin/(dashboard)/orders/[id]/pack/page';
const preview=makeOrderPreview(),id=preview.order.id,next='10000000-0000-4000-8000-000000000002';
beforeEach(()=>{vi.clearAllMocks();m.guard.mockResolvedValue({userId:'test'});m.order.mockResolvedValue(preview.order);m.global.mockResolvedValue({queue:[id],index:0,nextId:null,total:1,truncated:false});m.selected.mockResolvedValue({ids:[id,next],originalPosition:1,originalTotal:2,eligibleIds:[next],skippedIds:[id],nextId:next,returnTo:'/admin/orders?status=to_fulfil'});});afterEach(cleanup);
it('rejects invalid batches without reading order data or the global queue',async()=>{render(await PackPage({params:Promise.resolve({id}),searchParams:Promise.resolve({batch:'bad',returnTo:'https://evil.test'})}));expect(screen.getByText('This packing batch is invalid')).toBeVisible();expect(screen.getByRole('link',{name:'Back to orders'})).toHaveAttribute('href','/admin/orders');expect(m.order).not.toHaveBeenCalled();expect(m.global).not.toHaveBeenCalled();});
it('skips a changed selected order and carries only the batch forward',async()=>{m.order.mockResolvedValue({...preview.order,status:'cancelled'});render(await PackPage({params:Promise.resolve({id}),searchParams:Promise.resolve({batch:`${id},${next}`,returnTo:'/admin/orders?shipping=express'})}));expect(screen.getByText(/is cancelled/)).toBeVisible();expect(screen.getByText(/selected order skipped/)).toBeVisible();expect(screen.getByRole('link',{name:'Pack the next selected order'})).toHaveAttribute('href',expect.stringContaining(`batch=${id}%2C${next}`));expect(m.global).not.toHaveBeenCalled();expect(m.lots).not.toHaveBeenCalled();});
it('keeps direct legacy packing links on the global queue and guards all reads',async()=>{await PackPage({params:Promise.resolve({id})});expect(m.global).toHaveBeenCalledWith(id);expect(m.selected).not.toHaveBeenCalled();m.guard.mockRejectedValueOnce(Error('AUTH'));m.order.mockClear();await expect(PackPage({params:Promise.resolve({id})})).rejects.toThrow('AUTH');expect(m.order).not.toHaveBeenCalled();});
