"use client";
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowDownToLine,ArrowUpRight,RefreshCw,Clock3} from 'lucide-react';
import {METRICS,type FulfilmentParams,type FulfilmentReport,type TimingPage,type Metric} from '@/lib/admin/fulfilment-analytics/types';
import {compareStats,completeComparison,days,duration,localDate,periodLabel,timestamp} from '@/lib/admin/fulfilment-analytics/format';
import {fulfilmentHref} from '@/lib/admin/fulfilment-analytics/params';
import OrderTimings from './OrderTimings';
import TrendCharts from './TrendCharts';
import PeriodTable from './PeriodTable';

const control='min-h-9 rounded-lg border border-line bg-surface px-3 py-2 text-xs text-fg-2';
const viewLabels={waiting:'Paid, waiting',unpaid:'Awaiting payment',payments:'Payment history',shipments:'Shipment history',quality:'Timestamp checks'};
function Comparison({report,params}:{report:FulfilmentReport;params:FulfilmentParams}){
 const result=params.comparison==='matched'&&report.matched?compareStats(report.matched.previous.fulfilment,report.matched.current.fulfilment,params.stat):params.comparison==='complete'?completeComparison(report.periods,'fulfilment',params.stat):null;
 const full=completeComparison(report.periods,'fulfilment',params.stat);
 const label=params.comparison==='matched'?'Same point in previous period · provisional':full?`${periodLabel(full.currentKey,params.grain)} vs ${periodLabel(full.previousKey,params.grain)}`:'Two consecutive complete periods';
 return <div className="rounded-xl border border-line bg-surface/60 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-muted">Paid → marked shipped · {label}</p>{result?<p className="mt-1 text-base font-medium text-fg">{duration(Math.abs(result.delta))} {result.delta<0?'faster':result.delta>0?'slower':'change'}{result.percent!=null&&<span className="ml-2 text-sm text-muted">({Math.abs(result.percent).toFixed(1)}%)</span>}</p>:<p className="mt-1 text-sm text-fg-2">Not enough comparable history in this range.</p>}</div>{result&&<div className="text-xs text-muted">{result.previousCount} → {result.currentCount} orders{result.smallSample&&<span className="mt-1 block text-warn">Small sample · fewer than 10 orders</span>}</div>}</div></div>;
}
function Filters({params}:{params:FulfilmentParams}){
 const [range,setRange]=useState(params.range);
 return <form action="/admin/fulfilment" className="flex flex-wrap items-end gap-3 rounded-xl border border-line bg-surface/50 p-4">
  <input type="hidden" name="tab" value={params.tab}/><input type="hidden" name="view" value={params.view}/>
  <label className="space-y-1 text-xs text-muted"><span className="block">Group by</span><select name="grain" defaultValue={params.grain} className={control}><option value="week">Week</option><option value="month">Month</option></select></label>
  <label className="space-y-1 text-xs text-muted"><span className="block">Date range</span><select name="range" value={range} onChange={e=>setRange(e.target.value as FulfilmentParams['range'])} className={control}><option value="all">All history</option><option value="12w">Last 12 weeks</option><option value="12m">Last 12 months</option><option value="custom">Custom dates</option></select></label>
  {range==='custom'&&<><label className="min-w-0 space-y-1 text-xs text-muted"><span className="block">From</span><input className={`${control} max-w-full`} type="date" name="from" defaultValue={params.from??''} required/></label><label className="min-w-0 space-y-1 text-xs text-muted"><span className="block">To (inclusive)</span><input className={`${control} max-w-full`} type="date" name="to" defaultValue={params.to??''} required/></label></>}
  <label className="space-y-1 text-xs text-muted"><span className="block">Statistic</span><select name="stat" defaultValue={params.stat} className={control}><option value="median">Typical (median)</option><option value="mean">Average (mean)</option><option value="p90">90th percentile</option></select></label>
  <label className="space-y-1 text-xs text-muted"><span className="block">Compare</span><select name="comparison" defaultValue={params.comparison} className={`${control} max-w-full`}><option value="complete">Complete periods</option><option value="matched">Same point in previous period</option></select></label>
  <button type="submit" className="min-h-9 rounded-lg bg-accent px-4 py-2 text-xs font-medium text-accent-ink">Apply</button>
 </form>;
}
export default function FulfilmentDashboard({report,params,orders}:{report:FulfilmentReport;params:FulfilmentParams;orders:TimingPage}){
 const router=useRouter();
 const selected=report.periods.find(p=>p.key===params.period);
 const summary=selected??report.summary;
 const scope=selected?`${periodLabel(selected.key,params.grain)} · selected ${params.grain}`:`${report.from} – ${report.to}`;
 const historyLink=(metric:Metric)=>fulfilmentHref(params,{tab:'orders',view:metric==='payment'?'payments':'shipments',metric,sort:'milestone'});
 const exportLink=(kind:'orders'|'periods')=>fulfilmentHref(params,{},'/admin/fulfilment/export')+`&kind=${kind}&asOf=${encodeURIComponent(report.as_of)}`;
 const queueParams={...params,view:params.view==='unpaid'?'unpaid' as const:'waiting' as const,metric:null};
 return <div className="admin-stagger min-w-0 space-y-5 pb-10">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs text-accent"><Clock3 size={14}/> FULFILMENT EXPERIENCE</div><h2 className="text-2xl font-semibold tracking-tight text-fg">Every stage of the wait.</h2><p className="mt-1 text-sm text-muted">Order placed → payment confirmed → marked shipped</p></div><button type="button" onClick={()=>router.refresh()} className={`${control} flex items-center gap-2`}><RefreshCw size={14}/> Refresh</button></div>
  <nav className="flex gap-6 border-b border-line" aria-label="Fulfilment views">{(['overview','trends','orders'] as const).map(tab=><Link key={tab} href={fulfilmentHref(params,{tab,metric:tab==='orders'?params.metric:null})} aria-current={params.tab===tab?'page':undefined} className={`border-b-2 pb-3 text-sm ${params.tab===tab?'border-accent text-fg':'border-transparent text-muted hover:text-fg'}`}>{tab==='orders'?'Order timings':tab==='trends'?'Trends':'Overview'}</Link>)}</nav>
  <Filters key={`${params.range}:${params.grain}:${params.stat}:${params.from}:${params.to}:${params.comparison}:${params.tab}`} params={params}/>
  <div className="flex flex-wrap items-center justify-between gap-2 text-xs text-muted"><span>{report.first_order_at?`History available from ${localDate(report.first_order_at)}`:'No recorded orders yet'} · Australia/Sydney</span><span>Updated {timestamp(report.as_of)}</span></div>
  {selected&&<div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-accent/25 bg-accent/5 px-4 py-3 text-xs"><span>Selected {params.grain}: {periodLabel(selected.key,params.grain)}{selected.partial.length?' · partial period':''}</span><Link className="text-accent" href={fulfilmentHref(params,{period:null})}>Clear period selection</Link></div>}
  {report.quality.affected_orders>0&&<div role="status" className="rounded-lg border border-warn/30 bg-warn/5 p-4 text-xs leading-relaxed text-fg-2"><strong>{report.quality.affected_orders} orders need timestamp checks across all history.</strong> Missing payment: {report.quality.missing_payment}; missing shipment: {report.quality.missing_shipment}; invalid payment: {report.quality.invalid_payment}; invalid fulfilment: {report.quality.invalid_fulfilment}; invalid total: {report.quality.invalid_total}; future timestamps: {report.quality.future_timestamps}. Invalid intervals are excluded. <Link className="text-accent underline" href={fulfilmentHref(params,{tab:'orders',view:'quality',metric:null,period:null})}>Inspect affected orders</Link></div>}
  {params.tab!=='orders'&&<>
   <div className="flex flex-wrap justify-between gap-2"><p className="text-xs text-muted">{scope} · {params.stat==='median'?'Typical (median)':params.stat==='mean'?'Average (mean)':'90th percentile'}</p><Link href={exportLink('periods')} className="inline-flex items-center gap-1 text-xs text-fg-2 hover:text-accent"><ArrowDownToLine size={13}/> Export periods</Link></div>
   <div className="grid gap-3 sm:grid-cols-3">{METRICS.map(m=><div key={m.key} className={`admin-card rounded-xl p-4 ${m.key==='fulfilment'?'ring-1 ring-accent/40':''}`}><div className="text-xs text-muted">{m.label}</div><div className="mt-2 text-3xl font-medium tracking-tight tabular-nums text-fg">{days(summary[m.key][params.stat])}<span className="ml-1 text-xs tracking-normal text-muted">days</span></div><p className="mt-1 text-xs tabular-nums text-fg-2">{duration(summary[m.key][params.stat])}</p><p className="mt-3 text-[11px] text-muted">{m.basis}</p><Link href={historyLink(m.key)} className="mt-1 inline-block text-xs text-accent">{summary[m.key].n} valid of {m.key==='payment'?summary.paid_count:summary.shipped_count} recorded · view orders</Link>{summary[m.key].n>0&&summary[m.key].n<10&&<p className="mt-1 text-[11px] text-muted">Small sample</p>}</div>)}</div>
   <Comparison report={report} params={params}/>
  </>}
  {params.tab==='overview'&&<>
   <div className="grid gap-5 rounded-xl border border-line bg-surface/30 p-5 sm:grid-cols-[1.5fr_1fr]"><section><h3 className="text-sm font-medium">How long paid orders took</h3><p className="mt-1 text-xs text-muted">Share of valid shipments in the selected period</p><div className="mt-5 space-y-3">{['Up to 1 day','1–2 days','2–3 days','Over 3 days'].map((label,i)=>{const n=summary.distribution[i]??0;const pct=summary.fulfilment.n?n/summary.fulfilment.n*100:0;return <div key={label} className="grid grid-cols-[80px_1fr_65px] items-center gap-3 text-xs"><span className="text-muted">{label}</span><div className="h-2 overflow-hidden rounded bg-surface-2" role="img" aria-label={`${label}: ${n} orders`}><div className="h-full bg-accent/80" style={{width:`${pct}%`}}/></div><span className="text-right tabular-nums text-fg-2">{n} · {pct.toFixed(0)}%</span></div>;})}</div></section><section className="border-t border-line pt-4 sm:border-l sm:border-t-0 sm:pl-5 sm:pt-0"><h3 className="text-sm font-medium">The longer waits</h3><div className="mt-3 text-2xl font-medium tabular-nums">{duration(summary.fulfilment.p90)}</div><p className="mt-1 text-xs text-muted">90th percentile · paid to marked shipped</p><div className="mt-4 flex justify-between gap-3 text-xs"><span className="text-muted">Longest wait</span><span className="tabular-nums">{duration(summary.fulfilment.max)}</span></div></section></div>
   <section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-base font-medium text-fg">Waiting now</h3><p className="mt-1 text-xs text-muted">Current queue · all dates · longest wait first</p></div><Link className="inline-flex items-center gap-1 text-xs text-accent" href={fulfilmentHref(queueParams,{tab:'orders',period:null,sort:'wait',dir:'desc'})}>View full queue <ArrowUpRight size={14}/></Link></div><div className="flex flex-wrap gap-2">{(['waiting','unpaid'] as const).map(view=><Link key={view} href={fulfilmentHref(params,{view,metric:null,sort:'wait',dir:'desc'})} aria-current={queueParams.view===view?'page':undefined} className={`${control} ${queueParams.view===view?'border-accent/50 text-accent':''}`}>{viewLabels[view]} · {view==='waiting'?report.queues.paid:report.queues.unpaid}</Link>)}</div><OrderTimings page={orders} params={queueParams} preview/></section>
  </>}
  {params.tab==='trends'&&<>
   {report.periods.length?<div className="admin-card rounded-xl p-4 sm:p-5"><TrendCharts periods={report.periods} params={params}/></div>:<p className="rounded-lg border border-line p-8 text-center text-sm text-muted">No recorded history in this range.</p>}
   <PeriodTable periods={report.periods} params={params}/>
  </>}
  {params.tab==='orders'&&<section className="space-y-4">
   <div className="flex flex-wrap gap-2">{(Object.keys(viewLabels) as (keyof typeof viewLabels)[]).map(view=><Link key={view} href={fulfilmentHref(params,{view,metric:null,sort:view==='payments'||view==='shipments'?'milestone':'wait'})} aria-current={params.view===view?'page':undefined} className={`${control} ${params.view===view?'border-accent/50 text-accent':''}`}>{viewLabels[view]}</Link>)}</div>
   <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted">{['waiting','unpaid','quality'].includes(params.view)?'Current view · all dates':scope}{params.metric?` · valid ${METRICS.find(m=>m.key===params.metric)?.label} intervals`:''}</p><Link href={exportLink('orders')} className="inline-flex items-center gap-1 text-xs text-fg-2 hover:text-accent"><ArrowDownToLine size={13}/> Export orders</Link></div>
   <div className="flex flex-wrap items-center gap-3 text-xs text-muted"><span>Sort:</span>{(['payment','fulfilment','total','milestone'] as const).map(sort=><Link key={sort} href={fulfilmentHref(params,{sort,dir:params.sort===sort&&params.dir==='desc'?'asc':'desc'})} className={params.sort===sort?'text-accent':'hover:text-fg'}>{sort==='payment'?'Payment delay':sort==='fulfilment'?'Fulfilment delay':sort==='total'?'Total elapsed':'Milestone date'}{params.sort===sort?(params.dir==='desc'?' ↓':' ↑'):''}</Link>)}{params.metric&&<Link className="text-accent" href={fulfilmentHref(params,{metric:null})}>Include missing timings</Link>}</div>
   <OrderTimings page={orders} params={params}/>
  </section>}
  <details className="rounded-lg border border-line px-4 py-3 text-xs leading-relaxed text-muted"><summary className="cursor-pointer text-fg-2">How these timings are calculated</summary><p className="mt-3">One elapsed day is 24 hours, including weekends. Payment records when the team confirms it. Fulfilment records when the order is marked shipped; automatic completion does not establish delivery. Payment statistics group orders by payment date; fulfilment and total statistics group them by shipping date. Each metric shows its own count. Medians are calculated independently and cannot be added together.</p><p className="mt-2">The 90th percentile uses continuous interpolation. Historical refunds retain the original observed payment and shipping intervals. Open orders show a running wait and do not enter completed-duration statistics. Empty periods remain unknown, and missing or invalid timestamps are excluded with coverage shown. Comparisons are descriptive, with no service targets or claims of statistical significance.</p></details>
 </div>;
}
